ROOTDIR=../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=CommandLineExecutor.class \
	CPSIterator.class \
	Debug.class \
	FileUtils.class \
	INIFile.class \
	PropertyManager.class \
	StreamGobbler.class \
	StringConverter.class \
	Version.class

include ${ROOTDIR}default.mk
