ROOTDIR=../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=ContextRepositoryEntity.class \
	DataMap.class \
	DataStore.class \
	DeclaredRepositoryEntity.class \
	RepositoryEntity.class \
	TypedDeclaration.class

include ${ROOTDIR}default.mk
