ROOTDIR=../../../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=CtlChecker.class \
	CtlFormula.class \
	CtlFormulaVisitor.class \
	CtlParseException.class \
	CtlParser.class
	

include ${ROOTDIR}default.mk
