using System;
using System.IO;
using Microsoft.Win32;
using System.Reflection;

namespace AntHelper
{
	class MainClass
	{
		static int Main(string[] args)
		{
			if (args.Length == 0)
			{
				Console.Out.WriteLine("Usage: AntHelper [command]\n");
				Console.Out.WriteLine("Where [command] is one of the following:");
				Console.Out.WriteLine(" getsystemproperties <filename>");
				Console.Out.WriteLine("\tWrite out various system properties to <filename>");
				Console.Out.WriteLine(" lookupAssembly <assembly>");
				Console.Out.WriteLine("\tFind the full path to the requested assembly");
				return 1;
			}
			else if (args[0].Equals("getsystemproperties"))
			{
				return resolveGetSystemProperties(args);
			}
			else if (args[0].Equals("lookupAssembly"))
			{
				return lookupAssembly(args);
			}
			return 1;
		}

		static int resolveGetSystemProperties(string[] args)
		{
			string filename = "system.properties";
			if (args.Length > 1) filename = args[1];
			TextWriter propFile = new StreamWriter(filename, false);
			propFile.WriteLine("# Autogenerated file by AntHelper {0}", DateTime.Now);

			RegistryKey regKey = Registry.LocalMachine.OpenSubKey("Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Composestar", false);
			if (regKey != null)
			{
				string path = (string) regKey.GetValue("UninstallString");
				path = strReplace(path.Substring(0, path.LastIndexOf("\\")), "\\", "/");			
				propFile.WriteLine("composestar.installdir={0}", path);
			}
			else 
			{
				propFile.WriteLine("# Unable to retrieve the Compose* install directory");
			}

			propFile.Close();
			return 0;
		}

		static string strReplace(string input, string from, string to)
		{
			int i = input.IndexOf(from);
			while (i > -1)
			{
				input = input.Substring(0, i)+to+input.Substring(i+from.Length);
				i = input.IndexOf(from);
			}
			return input;
		}

		static int lookupAssembly(string[] args)
		{
			if (args.Length < 2) return 1;
			try 
			{
				Assembly asm = Assembly.LoadWithPartialName(args[1]);
				Console.Out.WriteLine("{0}", asm.Location);
				return 0;
			}
			catch (Exception)
			{
				return 2;
			}
		}
	}
}
