package Composestar.Core.CKRET;

import Composestar.Core.FILTH.FilterModuleOrder;
import Composestar.Core.CpsProgramRepository.Concern;

import java.io.Serializable;
import java.util.ArrayList;

/**
 * Semantic Reasoning Report generated by SECRET
 */
public class SECRETReport implements Serializable
{
	private FilterModuleOrder order;
	private FilterSetAnalysis analysis;
	private boolean selected;

	public SECRETReport(FilterModuleOrder order, FilterSetAnalysis analysis, boolean selected) 
	{
		this.order = order;
		this.analysis = analysis;
		this.selected = selected;

		this.addToConcern();
	}

	/**
	 * Adds this report to the set of reports of a concern
	 * The set is the dynamic object called 'SECRETReports'
	 */
	public void addToConcern()
	{
		Concern c = this.analysis.getConcern();
		ArrayList reports = (ArrayList)c.getDynObject("SECRETReports");
		// if this is not available yet, create it
		if (reports == null) 
		{
			reports = new ArrayList(); 
			c.addDynObject("SECRETReports", reports);
		}

		reports.add(this);
	}

	public FilterModuleOrder getOrder()
	{
		return this.order;		
	}

	public boolean getSelected()
	{
		return this.selected;		
	}

	public FilterSetAnalysis getAnalysis()
	{
		return this.analysis;		
	}
}

