ROOTDIR=../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=CMethodInfo.class CParameterInfo.class CVariable.class CDirectory.class CAnnotation.class CType.class CTypeMap.class CFile.class 
	
include ${ROOTDIR}default.mk
