ROOTDIR=../../../../
include ${ROOTDIR}common.mk

SUBDIRS=Config

CLASSES=INCRE.class \
	Dependency.class \
	ConfigNode.class \
	DynamicNode.class \
	FieldNode.class \
	MethodNode.class \
	FileDependency.class \
	Module.class \
	MyComparator.class \
	Node.class \
	ObjectDependency.class \
	INCRETimer.class \
	INCREReporter.class \
	Path.class \
	INCREConfigurations.class \
	INCRETester.class

include ${ROOTDIR}default.mk
