ROOTDIR=../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=DotNETAttribute.class \
	DotNETCallingConventions.class \
	DotNETFieldInfo.class \
	DotNETMethodInfo.class \
	DotNETModule.class \
	DotNETParameterInfo.class \
	DotNETType.class

include ${ROOTDIR}default.mk
