ROOTDIR=../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=ModifierException.class \
	Assembler.class \
	MSAssembler.class \
	ClassModifier.class \
	ILCodeParser.class \
	DummyUnlinker.class \
	DotNETSignatureTransformer.class \
	TransformerBase.class

include ${ROOTDIR}default.mk
