ROOTDIR=../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=AnnotatedEdge.class \
	AnnotatedNode.class \
	ExecutionModelExtractor.class \
	FirePreprocessingResult.class \
	FlowModelExtractor.class \
	GrooveASTBuilder.class \
	JarGpsGrammar.class \
	JarGpsGrammar$$InnerLoader.class\
	Preprocessor.class
	

include ${ROOTDIR}default.mk
