ROOTDIR=../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=Annotation.class \
	FieldInfo.class \
	LangNamespace.class \
	MethodInfo.class \
	ParameterInfo.class \
	ProgramElement.class \
	Type.class \
	TypeMap.class \
	UnitRegister.class \
	UnitResult.class \
	CallToOtherMethod.class \
	ResourceUsage.class

include ${ROOTDIR}default.mk
