package Composestar.Eclipse.Core.BuildConfiguration;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Properties;

import Composestar.Eclipse.Core.ComposestarEclipsePluginPlugin;
import Composestar.Eclipse.Core.Debug;
import Composestar.Eclipse.Core.IComposestarConstants;

/**
 * This class is responsible for creating a buildconfigurationfile
 */
@Deprecated
public class BuildConfigurationManager
{

	private static BuildConfigurationManager Instance = null;

	private ArrayList projects = new ArrayList();

	private ArrayList concernsources = new ArrayList();

	private Platform platform = null;

	private Settings settings = new Settings();

	public String buildconfigFile = "";

	private String applicationStart = "";

	private String buildDebugLevel = "";

	private String runDebugLevel = "";

	private String outputPath = "";

	private String platformConfigFile = "";

	public BuildConfigurationManager()
	{

	}

	public static BuildConfigurationManager instance()
	{
		if (Instance == null)
		{
			Instance = new BuildConfigurationManager();
		}
		return (Instance);
	}

	public void setPlatformConfigFile(String pcf)
	{
		platformConfigFile = pcf;
	}

	public void saveToXML(String fileName)
	{
		if (platformConfigFile.equals(""))
		{
			platformConfigFile = ComposestarEclipsePluginPlugin.getAbsolutePath("/PlatformConfigurations.xml");
		}
		try
		{
			Debug.instance().Log("Building configuration file...");
			this.buildconfigFile = fileName;
			BufferedWriter bw = new BufferedWriter(new FileWriter(fileName));
			bw.write("<?xml version=\"1.0\" encoding=\"us-ascii\"?>\n");
			bw
					.write("<!--This BuildConfiguration file is automatically generated by the Composestar Eclipse Plugin.-->\n");
			bw.write("<BuildConfiguration version=\"1.00\">\n");

			// projects
			bw.write(spacePad(1) + "<Projects buildDebugLevel=\"" + buildDebugLevel + "\" applicationStart=\""
					+ applicationStart + "\" runDebugLevel=\"" + runDebugLevel + "\" outputPath=\"" + outputPath
					+ "\">\n");
			Iterator projIt = projects.iterator();
			while (projIt.hasNext())
			{
				Project p = (Project) projIt.next();
				bw.write(spacePad(2) + "<Project ");
				Properties props = p.getProperties();
				Iterator pkeys = props.keySet().iterator();
				while (pkeys.hasNext())
				{
					String key = (String) pkeys.next();
					String value = p.getProperty(key);
					bw.write(key + "=\"" + value + "\" ");
				}
				bw.write(">\n");

				// sources
				bw.write(spacePad(3) + "<Sources>\n");
				ArrayList sources = p.getSources();
				Iterator sourceIt = sources.iterator();
				while (sourceIt.hasNext())
				{
					String source = (String) sourceIt.next();
					bw.write(spacePad(4) + "<Source fileName=\"" + source + "\" />\n");
				}
				bw.write(spacePad(3) + "</Sources>\n");

				// dependencies
				bw.write(spacePad(3) + "<Dependencies>\n");
				ArrayList deps = p.getDependencies();
				Iterator depIt = deps.iterator();
				while (depIt.hasNext())
				{
					String dep = (String) depIt.next();
					bw.write(spacePad(4) + "<Dependency fileName=\"" + dep + "\" />\n");
				}
				bw.write(spacePad(3) + "</Dependencies>\n");

				// type sources
				bw.write(spacePad(3) + "<TypeSources>\n");
				ArrayList typeSources = p.getTypeSources();
				Iterator typeIt = typeSources.iterator();
				String name = "";
				String file = "";
				while (typeIt.hasNext())
				{
					TypeSource t = (TypeSource) typeIt.next();
					name = t.getName();
					file = t.getFileName();
					bw.write(spacePad(4) + "<TypeSource name=\"" + name + "\" fileName=\"" + file + "\" />\n");
				}
				bw.write(spacePad(3) + "</TypeSources>\n");
				bw.write(spacePad(2) + "</Project>\n");
			}
			// concern sources
			bw.write(spacePad(2) + "<ConcernSources>\n");
			Iterator csourceIt = this.concernsources.iterator();
			while (csourceIt.hasNext())
			{
				String csource = (String) csourceIt.next();
				bw.write(spacePad(3) + "<ConcernSource fileName=\"" + csource + "\" />\n");
			}
			bw.write(spacePad(2) + "</ConcernSources>\n");
			bw.write(spacePad(1) + "</Projects>\n");

			// settings
			HashMap globalSettings = settings.getSettings();
			Iterator settingsIt = globalSettings.keySet().iterator();
			if (!settingsIt.hasNext())
			{
				bw.write(spacePad(1) + "<Settings>\n");
			}
			else
			{
				bw.write(spacePad(1) + "<Settings");
				while (settingsIt.hasNext())
				{
					String key = (String) settingsIt.next();
					String value = (String) globalSettings.get(key);
					bw.write(" " + key + "=" + "\"" + value + "\"");
				}
				bw.write(">\n");
			}
			// module settings
			bw.write(spacePad(2) + "<Modules>\n");
			HashMap moduleSettings = settings.getModuleSettings();
			Iterator modules = moduleSettings.keySet().iterator();
			while (modules.hasNext())
			{
				String key = (String) modules.next();
				HashMap msettings = (HashMap) moduleSettings.get(key);

				StringBuffer buf = new StringBuffer();
				buf.append(spacePad(3) + "<Module name=\"" + key + "\" ");

				Iterator keySet = msettings.keySet().iterator();
				while (keySet.hasNext())
				{
					Object o = keySet.next();
					String s = (String) msettings.get(o);
					buf.append("" + o + "=\"" + s + "\" ");
				}
				buf.append("/>\n");
				bw.write(buf.toString());
			}
			bw.write(spacePad(2) + "</Modules>\n");

			// paths
			bw.write(spacePad(2) + "<Paths>\n");
			Iterator paths = settings.getPaths().iterator();
			while (paths.hasNext())
			{
				Path p = (Path) paths.next();
				bw.write(spacePad(3) + "<Path name=\"" + p.getName() + "\" pathName=\"" + p.getPath() + "\" />\n");
			}
			bw.write(spacePad(2) + "</Paths>\n");

			bw.write(spacePad(1) + "</Settings>\n");

			BufferedReader in = new BufferedReader(new FileReader(platformConfigFile));
			String s;
			StringBuffer buffer = new StringBuffer();
			boolean skip = true;

			String pluginPath = ComposestarEclipsePluginPlugin.getAbsolutePath("");
			while ((s = in.readLine()) != null)
			{
				if (s.startsWith("<Platforms>"))
				{
					// Replace %composestar% with the core plugin path (where
					// the binaries are)
					s = s.replaceAll("%composestar%", pluginPath);
					buffer.append(spacePad(1) + "" + s + "\n");
					skip = false;
				}
				else if (!skip)
				{
					buffer.append(s + "\n");
				}
			}
			bw.write(buffer.toString());

			bw.write("</BuildConfiguration>\n");
			bw.close();
		}
		catch (IOException io)
		{
			Debug.instance().Log("Error while creating BuildConfigurationFile: " + io.getMessage(),
					IComposestarConstants.MSG_ERROR);
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}

	// helper method
	private String spacePad(int level)
	{
		String spaces = "  ";
		StringBuffer s = new StringBuffer();
		for (int i = 0; i < level; i++)
		{
			s.append(spaces);
		}
		return s.toString();
	}

	public void setProject(Project proj)
	{
		projects.add(proj);
	}

	public void clearConfigManager()
	{
		projects.clear();
		concernsources.clear();
		settings.clearPaths();
		platformConfigFile = "";
	}

	public void setConcernSources(String source)
	{
		concernsources.add(source);
	}

	public void addPath(Path p)
	{
		settings.addPath(p);
	}

	public void addSetting(String key, String value)
	{
		settings.addSetting(key, value);
	}

	public void addModuleSetting(ModuleSetting ms)
	{
		settings.addModuleSetting(ms);
	}

	public void setApplicationStart(String applicationStart)
	{
		this.applicationStart = applicationStart;
	}

	public Platform getPlatform(String name)
	{
		if (platform == null)
		{
			loadPlatform(name);
		}
		else if (!platform.getName().equals(name))
		{
			loadPlatform(name);
		}
		return platform;
	}

	public void loadPlatform(String name)
	{
		if (platformConfigFile.equals(""))
		{
			platformConfigFile = ComposestarEclipsePluginPlugin.getAbsolutePath("/PlatformConfigurations.xml");
		}
		platform = new Platform(name);
		platform.readPlatform(platformConfigFile);
	}

	public void setBuildDebugLevel(String buildDebugLevel)
	{
		this.buildDebugLevel = buildDebugLevel;
	}

	public void setRunDebugLevel(String runDebugLevel)
	{
		this.runDebugLevel = runDebugLevel;
	}

	public void setOutputPath(String outputPath)
	{
		this.outputPath = outputPath;
	}

}
