ROOTDIR=../../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=ConcernElementReference.class \
	ConcernReference.class \
	ConditionReference.class \
        DeclaredObjectReference.class \
        FilterModuleElementReference.class \
        FilterModuleReference.class \
        FilterReference.class \
        LabeledConcernReference.class \
        MethodReference.class \
        ProgramElementReference.class \
        Reference.class \
        SelectorReference.class

include ${ROOTDIR}default.mk
