ROOTDIR=../../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=Labeler.class \
	LabelSequence.class \
	Matcher.class \
	Pattern.class \
	PatternParseException.class
	

include ${ROOTDIR}default.mk
