ROOTDIR=../../../../
include ${ROOTDIR}common.mk

SUBDIRS=parsing utils

CLASSES=CWrapper.class \
	ExitPoint.class \
	Function.class \
	FunctionFactory.class \
	GlobalIntroductionPoint.class \
	InputFileNameFilter.class \
	Parameter.class \
	ParameterType.class \
	Struct.class \
	WeaveblePoint.class

include ${ROOTDIR}default.mk
