ROOTDIR=../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=BaseChecker.class \
	DoCheck.class \
	DoubleNames.class \
	Main.class \
	ExistCondition.class \
	ExistFilterModule.class \
	NotUsedCondition.class \
	NotUsedExternals.class \
	NotUsedInternals.class \
	NotUsedSelector.class

include ${ROOTDIR}default.mk
