ROOTDIR=../../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=ActionsHandler.class \
	BuildXMLHandler.class \
	CompilerHandler.class \
	ConcernSourcesHandler.class \
	ConvertersHandler.class \
	CustomFiltersHandler.class \
	FileExtensionsHandler.class \
	LanguageHandler.class \
	ModulesHandler.class \
	PathsHandler.class \
	PlatformHandler.class \
	ProjectConfigurationHandler.class \
	ProjectDependenciesHandler.class \
	ProjectHandler.class \
	ProjectSourcesHandler.class \
	RequiredFilesHandler.class \
	SettingsHandler.class


# Default make
include ${ROOTDIR}default.mk
