ROOTDIR=../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=ActionsHandler.class \
	      ConfigParser.class \
	      ConstraintsHandler.class \
	      FiltersHandler.class

include ${ROOTDIR}default.mk
