ROOTDIR=../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=ConfigManager.class \
	INCREXMLParser.class \
	ModulesHandler.class \
	ComparisonsHandler.class \
	ComparisonsPathHandler.class \
	DependencyHandler.class \
	PathHandler.class \
	TypeHandler.class

include ${ROOTDIR}default.mk
