ROOTDIR=../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=CCodeWrapper.class CSymbolTable.class CToken.class GnuCEmitter.class GnuCEmitterTokenTypes.class GnuCLexerTokenTypes.class GnuCTokenTypes.class GnuCTreeParserTokenTypes.class LineObject.class ParserTest.class PreprocessorInfoChannel.class StdCLexer.class StdCParser.class StdCParser.class STDCTokenTypes.class TNode.class TNodeFactory.class WrappedAST.class GnuCLexer.class 

include ${ROOTDIR}default.mk
