ROOTDIR=../../../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=SimpleSelExpression.class \
	SelClass.class \
	SelClassAndSubClasses.class \
	PredicateSelector.class

include ${ROOTDIR}default.mk
