ROOTDIR=../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=XmlHandlers

CLASSES=BuiltLibraries.class \
	CompilerAction.class \
	CompilerConverter.class \
	CompilerSettings.class \
	ConcernSource.class \
	Configuration.class \
	CustomFilter.class \
	CustomFilters.class \
	Dependency.class \
	Language.class \
	Module.class \
	ModuleSettings.class \
	PathSettings.class \
	Platform.class \
	Project.class \
	Projects.class \
	Source.class \
	TypeSource.class


# Default make
include ${ROOTDIR}default.mk
