//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composestar.StarLight.Weaving.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Composestar.StarLight.Weaving.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find method named &apos;{0}(JoinpointContext)&apos; in type &apos;{1}&apos;.
        /// </summary>
        internal static string AdviceMethodNotFound {
            get {
                return ResourceManager.GetString("AdviceMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve filter action named &apos;{0}&apos;. .
        /// </summary>
        internal static string CouldNotResolveFilterAction {
            get {
                return ResourceManager.GetString("CouldNotResolveFilterAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} could not be found..
        /// </summary>
        internal static string FieldNotFound {
            get {
                return ResourceManager.GetString("FieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Parameter which requires no parameters..
        /// </summary>
        internal static string FMCEmptyDescription {
            get {
                return ResourceManager.GetString("FMCEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Condition Parameter requires a boolean function with no parameters..
        /// </summary>
        internal static string FMCEmptyRequired {
            get {
                return ResourceManager.GetString("FMCEmptyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Parameter with the fully qualified name of the current executing method..
        /// </summary>
        internal static string FMCFQNDescription {
            get {
                return ResourceManager.GetString("FMCFQNDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Condition Parameter requires a boolean function with a string as parameter..
        /// </summary>
        internal static string FMCFQNRequired {
            get {
                return ResourceManager.GetString("FMCFQNRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Parameter with a MethodBase object as its parameter..
        /// </summary>
        internal static string FMCMethodInfoDescription {
            get {
                return ResourceManager.GetString("FMCMethodInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Condition Parameter requires a boolean function with one parameter with as its type a System.Reflection.MethodBase. This will contain the current MethodInfo object..
        /// </summary>
        internal static string FMCMethodInfoRequired {
            get {
                return ResourceManager.GetString("FMCMethodInfoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Parameter with the namespace of the current executing method..
        /// </summary>
        internal static string FMCNSDescription {
            get {
                return ResourceManager.GetString("FMCNSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Condition Parameter requires a boolean function with two string parameters. The first one will contain the namespace, the second one the type..
        /// </summary>
        internal static string FMCNSRequired {
            get {
                return ResourceManager.GetString("FMCNSRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set inner call context for method &apos;{0}&apos; calling method &apos;{1}&apos;.
        /// </summary>
        internal static string SetInnerCallFailed {
            get {
                return ResourceManager.GetString("SetInnerCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} could not be found..
        /// </summary>
        internal static string TypeNotFound {
            get {
                return ResourceManager.GetString("TypeNotFound", resourceCulture);
            }
        }
    }
}
