ROOTDIR=../../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=SimpleSelectorDef

CLASSES=Binding.class \
	AnnotationBinding.class \
	ConditionBinding.class \
	FilterModuleBinding.class \
	MethodBinding.class \
        SelectorDefinition.class \
        StarCondition.class \
        StarMethod.class \
        SuperImposition.class

include ${ROOTDIR}default.mk
