ROOTDIR=../../../../
include ${ROOTDIR}common.mk

SUBDIRS=Config

CLASSES= AbstractVM.class \
	ConcernAnalysis.class \
	ExecutionAnalysis.class \
	FilterAction.class \
	FilterActionDescription.class \
	FilterInfo.class \
	FilterSetAnalysis.class \
	HTMLReporter.class \
	MessageAnalysis.class \
	MetaFilterAction.class \
	Operation.class \
	OrderAnalysis.class \
	Reporter.class \
	Repository.class \
	Resource.class \
	Scenario.class \
	SECRETReport.class \
	SECRET.class \
	StateAnalysis.class

include ${ROOTDIR}default.mk
