ROOTDIR=../../../../
include ${ROOTDIR}common.mk


SUBDIRS=

CLASSES=Acting.class \
	AttributeAnalyser.class \
	BehaviorSyntaxException.class \
	Resource.class \
	UnknownResourceException.class
		
#ASSEMBLIES=Reasoning.dll

# TODO also remove the .exe files.
include ${ROOTDIR}default.mk
