ROOTDIR=../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=DepthFirstIterator.class \
	FireAnalysis$$AnalysisState.class \
	FireAnalysis$$AnalysisTransition.class \
	FireAnalysis.class
	

include ${ROOTDIR}default.mk
