// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Composestar.StarLight.Entities.WeaveSpec.Instructions;
using Composestar.StarLight.Entities.WeaveSpec.Instructions.Visitor;
namespace TestStarLightEntities
{
    /// <summary>
    ///This is a test class for Composestar.StarLight.Entities.WeaveSpec.Instructions.ContextInstruction and is intended
    ///to contain all Composestar.StarLight.Entities.WeaveSpec.Instructions.ContextInstruction Unit Tests
    ///</summary>
    [TestClass()]
    public class ContextInstructionFixture
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for Accept (IVisitor)
        ///</summary>
        [TestMethod()]
        public void AcceptTest()
        {
            ContextInstruction target = new ContextInstruction();

            IVisitor visitor = null; // TODO: Initialize to an appropriate value

            target.Accept(visitor);

            Assert.Inconclusive("A method that does not return a value cannot be verified.");
        }

        /// <summary>
        ///A test for Code
        ///</summary>
        [TestMethod()]
        public void CodeTest()
        {
            ContextInstruction target = new ContextInstruction();

            int val = 0; // TODO: Assign to an appropriate value for the property

            target.Code = val;


            Assert.AreEqual(val, target.Code, "Composestar.StarLight.Entities.WeaveSpec.Instructions.ContextInstruction.Code was" +
                    " not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for ContextInstruction ()
        ///</summary>
        [TestMethod()]
        public void ConstructorTest()
        {
            ContextInstruction target = new ContextInstruction();

            // TODO: Implement code to verify target
            Assert.Inconclusive("TODO: Implement code to verify target");
        }

        /// <summary>
        ///A test for ContextInstruction (ContextType, int, Block)
        ///</summary>
        [TestMethod()]
        public void ConstructorTest1()
        {
            ContextType type = ContextType.Removed; // TODO: Initialize to an appropriate value

            int code = 0; // TODO: Initialize to an appropriate value

            Block innerBlock = null; // TODO: Initialize to an appropriate value

            ContextInstruction target = new ContextInstruction(type, code, innerBlock);

            // TODO: Implement code to verify target
            Assert.Inconclusive("TODO: Implement code to verify target");
        }

        /// <summary>
        ///A test for InnerBlock
        ///</summary>
        [TestMethod()]
        public void InnerBlockTest()
        {
            ContextInstruction target = new ContextInstruction();

            Block val = null; // TODO: Assign to an appropriate value for the property

            target.InnerBlock = val;


            Assert.AreEqual(val, target.InnerBlock, "Composestar.StarLight.Entities.WeaveSpec.Instructions.ContextInstruction.InnerBlo" +
                    "ck was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Type
        ///</summary>
        [TestMethod()]
        public void TypeTest()
        {
            ContextInstruction target = new ContextInstruction();

            ContextType val = ContextType.Removed; // TODO: Assign to an appropriate value for the property

            target.Type = val;


            Assert.AreEqual(val, target.Type, "Composestar.StarLight.Entities.WeaveSpec.Instructions.ContextInstruction.Type was" +
                    " not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

    }


}
