// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Composestar.StarLight.Entities.LanguageModel;
namespace TestStarLightEntities
{
    /// <summary>
    ///This is a test class for Composestar.StarLight.Entities.LanguageModel.FieldElement and is intended
    ///to contain all Composestar.StarLight.Entities.LanguageModel.FieldElement Unit Tests
    ///</summary>
    [TestClass()]
    public class FieldElementFixture
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for IsPrivate
        ///</summary>
        [TestMethod()]
        public void IsPrivateTest()
        {
            FieldElement target = new FieldElement();

            bool val = false; // TODO: Assign to an appropriate value for the property

            target.IsPrivate = val;


            Assert.AreEqual(val, target.IsPrivate, "Composestar.StarLight.Entities.LanguageModel.FieldElement.IsPrivate was not set c" +
                    "orrectly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for IsPublic
        ///</summary>
        [TestMethod()]
        public void IsPublicTest()
        {
            FieldElement target = new FieldElement();

            bool val = false; // TODO: Assign to an appropriate value for the property

            target.IsPublic = val;


            Assert.AreEqual(val, target.IsPublic, "Composestar.StarLight.Entities.LanguageModel.FieldElement.IsPublic was not set co" +
                    "rrectly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for IsStatic
        ///</summary>
        [TestMethod()]
        public void IsStaticTest()
        {
            FieldElement target = new FieldElement();

            bool val = false; // TODO: Assign to an appropriate value for the property

            target.IsStatic = val;


            Assert.AreEqual(val, target.IsStatic, "Composestar.StarLight.Entities.LanguageModel.FieldElement.IsStatic was not set co" +
                    "rrectly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Name
        ///</summary>
        [TestMethod()]
        public void NameTest()
        {
            FieldElement target = new FieldElement();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Name = val;


            Assert.AreEqual(val, target.Name, "Composestar.StarLight.Entities.LanguageModel.FieldElement.Name was not set correc" +
                    "tly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Type
        ///</summary>
        [TestMethod()]
        public void TypeTest()
        {
            FieldElement target = new FieldElement();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Type = val;


            Assert.AreEqual(val, target.Type, "Composestar.StarLight.Entities.LanguageModel.FieldElement.Type was not set correc" +
                    "tly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

    }


}
