// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Composestar.StarLight.Entities.Configuration;
namespace TestStarLightEntities
{
    /// <summary>
    ///This is a test class for Composestar.StarLight.Entities.Configuration.FilterActionElement and is intended
    ///to contain all Composestar.StarLight.Entities.Configuration.FilterActionElement Unit Tests
    ///</summary>
    [TestClass()]
    public class FilterActionElementFixture
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for Assembly
        ///</summary>
        [TestMethod()]
        public void AssemblyTest()
        {
            FilterActionElement target = new FilterActionElement();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Assembly = val;


            Assert.AreEqual(val, target.Assembly, "Composestar.StarLight.Entities.Configuration.FilterActionElement.Assembly was not" +
                    " set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for FlowBehavior
        ///</summary>
        [TestMethod()]
        public void FlowBehaviorTest()
        {
            FilterActionElement target = new FilterActionElement();

            int val = 0; // TODO: Assign to an appropriate value for the property

            target.FlowBehavior = val;


            Assert.AreEqual(val, target.FlowBehavior, "Composestar.StarLight.Entities.Configuration.FilterActionElement.FlowBehavior was" +
                    " not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for FullName
        ///</summary>
        [TestMethod()]
        public void FullNameTest()
        {
            FilterActionElement target = new FilterActionElement();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.FullName = val;


            Assert.AreEqual(val, target.FullName, "Composestar.StarLight.Entities.Configuration.FilterActionElement.FullName was not" +
                    " set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for MessageChangeBehavior
        ///</summary>
        [TestMethod()]
        public void MessageChangeBehaviorTest()
        {
            FilterActionElement target = new FilterActionElement();

            int val = 0; // TODO: Assign to an appropriate value for the property

            target.MessageChangeBehavior = val;


            Assert.AreEqual(val, target.MessageChangeBehavior, "Composestar.StarLight.Entities.Configuration.FilterActionElement.MessageChangeBeh" +
                    "avior was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Name
        ///</summary>
        [TestMethod()]
        public void NameTest()
        {
            FilterActionElement target = new FilterActionElement();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Name = val;


            Assert.AreEqual(val, target.Name, "Composestar.StarLight.Entities.Configuration.FilterActionElement.Name was not set" +
                    " correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

    }


}
