// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Composestar.StarLight.Entities.WeaveSpec;
namespace TestStarLightEntities
{
    /// <summary>
    ///This is a test class for Composestar.StarLight.Entities.WeaveSpec.Reference and is intended
    ///to contain all Composestar.StarLight.Entities.WeaveSpec.Reference Unit Tests
    ///</summary>
    [TestClass()]
    public class ReferenceFixture
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for Assembly
        ///</summary>
        [TestMethod()]
        public void AssemblyTest()
        {
            Reference target = new Reference();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Assembly = val;


            Assert.AreEqual(val, target.Assembly, "Composestar.StarLight.Entities.WeaveSpec.Reference.Assembly was not set correctly" +
                    ".");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Fullname
        ///</summary>
        [TestMethod()]
        public void FullnameTest()
        {
            Reference target = new Reference();

            string val = null; // TODO: Assign to an appropriate value for the property


            Assert.AreEqual(val, target.Fullname, "Composestar.StarLight.Entities.WeaveSpec.Reference.Fullname was not set correctly" +
                    ".");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for InnerCallContext
        ///</summary>
        [TestMethod()]
        public void InnerCallContextTest()
        {
            Reference target = new Reference();

            int val = 0; // TODO: Assign to an appropriate value for the property

            target.InnerCallContext = val;


            Assert.AreEqual(val, target.InnerCallContext, "Composestar.StarLight.Entities.WeaveSpec.Reference.InnerCallContext was not set c" +
                    "orrectly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for NameSpace
        ///</summary>
        [TestMethod()]
        public void NameSpaceTest()
        {
            Reference target = new Reference();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.NameSpace = val;


            Assert.AreEqual(val, target.NameSpace, "Composestar.StarLight.Entities.WeaveSpec.Reference.NameSpace was not set correctl" +
                    "y.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Reference ()
        ///</summary>
        [TestMethod()]
        public void ConstructorTest()
        {
            Reference target = new Reference();

            // TODO: Implement code to verify target
            Assert.Inconclusive("TODO: Implement code to verify target");
        }

        /// <summary>
        ///A test for Selector
        ///</summary>
        [TestMethod()]
        public void SelectorTest()
        {
            Reference target = new Reference();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Selector = val;


            Assert.AreEqual(val, target.Selector, "Composestar.StarLight.Entities.WeaveSpec.Reference.Selector was not set correctly" +
                    ".");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Target
        ///</summary>
        [TestMethod()]
        public void TargetTest()
        {
            Reference target = new Reference();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Target = val;


            Assert.AreEqual(val, target.Target, "Composestar.StarLight.Entities.WeaveSpec.Reference.Target was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

    }


}
