// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Composestar.StarLight.Entities.WeaveSpec;
using Composestar.StarLight.Entities.WeaveSpec.Instructions;
namespace TestStarLightEntities
{
    /// <summary>
    ///This is a test class for Composestar.StarLight.Entities.WeaveSpec.WeaveMethod and is intended
    ///to contain all Composestar.StarLight.Entities.WeaveSpec.WeaveMethod Unit Tests
    ///</summary>
    [TestClass()]
    public class WeaveMethodFixture
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for Calls
        ///</summary>
        [TestMethod()]
        public void CallsTest()
        {
            WeaveMethod target = new WeaveMethod();

            System.Collections.Generic.List<Composestar.StarLight.Entities.WeaveSpec.WeaveCall> val = null; // TODO: Assign to an appropriate value for the property

            target.Calls = val;


            Assert.AreEqual(val, target.Calls, "Composestar.StarLight.Entities.WeaveSpec.WeaveMethod.Calls was not set correctly." +
                    "");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for HasInputFilters
        ///</summary>
        [TestMethod()]
        public void HasInputFiltersTest()
        {
            WeaveMethod target = new WeaveMethod();

            bool val = false; // TODO: Assign to an appropriate value for the property


            Assert.AreEqual(val, target.HasInputFilters, "Composestar.StarLight.Entities.WeaveSpec.WeaveMethod.HasInputFilters was not set " +
                    "correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for HasOutputFilters
        ///</summary>
        [TestMethod()]
        public void HasOutputFiltersTest()
        {
            WeaveMethod target = new WeaveMethod();

            bool val = false; // TODO: Assign to an appropriate value for the property


            Assert.AreEqual(val, target.HasOutputFilters, "Composestar.StarLight.Entities.WeaveSpec.WeaveMethod.HasOutputFilters was not set" +
                    " correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for InputFilter
        ///</summary>
        [TestMethod()]
        public void InputFilterTest()
        {
            WeaveMethod target = new WeaveMethod();

            InlineInstruction val = null; // TODO: Assign to an appropriate value for the property

            target.InputFilter = val;


            Assert.AreEqual(val, target.InputFilter, "Composestar.StarLight.Entities.WeaveSpec.WeaveMethod.InputFilter was not set corr" +
                    "ectly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Signature
        ///</summary>
        [TestMethod()]
        public void SignatureTest()
        {
            WeaveMethod target = new WeaveMethod();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.Signature = val;


            Assert.AreEqual(val, target.Signature, "Composestar.StarLight.Entities.WeaveSpec.WeaveMethod.Signature was not set correc" +
                    "tly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

    }


}
