// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Composestar.StarLight.Entities.WeaveSpec.Instructions;
using Composestar.StarLight.Entities.WeaveSpec.Instructions.Visitor;
namespace TestStarLightEntities
{
    /// <summary>
    ///This is a test class for Composestar.StarLight.Entities.WeaveSpec.Instructions.While and is intended
    ///to contain all Composestar.StarLight.Entities.WeaveSpec.Instructions.While Unit Tests
    ///</summary>
    [TestClass()]
    public class WhileFixture
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for Accept (IVisitor)
        ///</summary>
        [TestMethod()]
        public void AcceptTest()
        {
            WhileInstruction target = new WhileInstruction();

            IVisitor visitor = null; // TODO: Initialize to an appropriate value

            target.Accept(visitor);

            Assert.Inconclusive("A method that does not return a value cannot be verified.");
        }

        /// <summary>
        ///A test for Expression
        ///</summary>
        [TestMethod()]
        public void ExpressionTest()
        {
            WhileInstruction target = new WhileInstruction();

            ContextExpression val = ContextExpression.HasMoreActions; // TODO: Assign to an appropriate value for the property

            target.Expression = val;


            Assert.AreEqual(val, target.Expression, "Composestar.StarLight.Entities.WeaveSpec.Instructions.While.Expression was not se" +
                    "t correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Instructions
        ///</summary>
        [TestMethod()]
        public void InstructionsTest()
        {
            WhileInstruction target = new WhileInstruction();

            Block val = null; // TODO: Assign to an appropriate value for the property

            target.Instructions = val;


            Assert.AreEqual(val, target.Instructions, "Composestar.StarLight.Entities.WeaveSpec.Instructions.While.Instructions was not " +
                    "set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for While ()
        ///</summary>
        [TestMethod()]
        public void ConstructorTest()
        {
            WhileInstruction target = new WhileInstruction();

            // TODO: Implement code to verify target
            Assert.Inconclusive("TODO: Implement code to verify target");
        }

        /// <summary>
        ///A test for While (ContextExpression, Block)
        ///</summary>
        [TestMethod()]
        public void ConstructorTest1()
        {
            ContextExpression expression = ContextExpression.HasMoreActions; // TODO: Initialize to an appropriate value

            Block instructions = null; // TODO: Initialize to an appropriate value

            WhileInstruction target = new WhileInstruction(expression, instructions);

            // TODO: Implement code to verify target
            Assert.Inconclusive("TODO: Implement code to verify target");
        }

    }


}
