ROOTDIR=../../../../
include ${ROOTDIR}common.mk

SUBDIRS=CpsConcern

CLASSES=Concern.class \
	PlatformRepresentation.class \
	PrimitiveConcern.class \
	Signature.class \
	SignatureImplementation.class \
	MethodWrapper.class

include ${ROOTDIR}default.mk
