ROOTDIR=../../../
include ${ROOTDIR}common.mk

SUBDIRS=COPPER ACTING CHKREP CKRET CONE CpsProgramRepository Exception EMBEX FILTH FIRE INCRE LAMA LOLA Master RepositoryImplementation REXREF SANE SIGN TYM WEAVER COMP BACO DUMMER
CLASSES= 

include ${ROOTDIR}default.mk
