ROOTDIR=../../../../
include ${ROOTDIR}common.mk

src:
	cd ltl&&${MAKE} src&&cd ..
	cd reg&&${MAKE} src&&cd ..

clean:
	cd ltl&&${MAKE} clean&&cd ..
	cd reg&&${MAKE} clean&&cd ..

include ${ROOTDIR}default.mk
