ROOTDIR=../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=TraceableType.class \
	TraceTypesDB.class \
	TraceTypesReader.class \
	TracingAspect.class \
	WeaveCAspect.class 

include ${ROOTDIR}default.mk
