ROOTDIR=../../../../
include ${ROOTDIR}common.mk

SUBDIRS=XMLSpecification Core

CLASSES=FILTHService.class \
	FILTH.class \
	FILTHServiceImpl.class \
	FilterModuleOrder.class \
	InnerDispatcher.class

include ${ROOTDIR}default.mk
