ROOTDIR=../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=Action.class \
	Edge.class \
	False.class \
	Parameter.class \
	Node.class \
	ExecutionManager.class \
	Graph.class \
	HardCondRule.class \
	HardPreRule.class \
	HardSkipRule.class \
	OrderTraverser.class \
	Rule.class \
	SkipRule.class \
	SoftCondRule.class \
	SoftPreRule.class \
	SoftSkipRule.class \
	True.class

include ${ROOTDIR}default.mk
