ROOTDIR=../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=SecretFiltersXMLHandler.class \
	SecretNonConflictStringsXMLHandler.class \
	SecretActionsXMLHandler.class \
	SecretFilterXMLParser.class

include ${ROOTDIR}default.mk
