ROOTDIR=../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=CompositeLanguageUnitType.class \
	CompositeRelationPredicate.class \
	InvalidModelException.class \
	LanguageModel.class \
	LanguageUnitType.class \
	ModelClashException.class \
	ModelException.class \
	RelationPredicate.class \
	RelationType.class \
	UnitDictionary.class

include ${ROOTDIR}default.mk
