ROOTDIR=../../../../
include ${ROOTDIR}common.mk

SUBDIRS= 
CLASSES= CCONE.class CRepositorySerializer.class CWeaveFileGenerator.class DispatchSemantic.class InputFileNameFilter.class Semantic.class WeaverEngine.class WeavingInstruction.class TestSemantic.class

include ${ROOTDIR}default.mk
