ROOTDIR=../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=Advice.class \
	AdviceApplication.class \
	AdviceFactory.class \
	Aspect.class \
	AspectReader.class \
	Functions.class \
	InputFileNameFilter.class \
	Pointcut.class \
	PointcutFactory.class \
	Scope.class \
	SpecificationFileNameFilter.class \
	WeavingPoint.class \
	XMLParameter.class

include ${ROOTDIR}default.mk
