ROOTDIR=../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=SANE.class \
	FilterModSIinfo.class \
	AbstractSIinfo.class \
	MethodSIinfo.class \
	ConditionSIinfo.class \
	SIinfo.class

include ${ROOTDIR}default.mk
