ROOTDIR=../../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=AbstractPattern.class \
	And.class \
	BooleanOclExpression.class \
	Condition.class \
	ConditionExpression.class \
	ConditionLiteral.class \
	CORfilterElementCompOper.class \
	DisableOperator.class \
	EnableOperator.class \
	EnableOperatorType.class \
        External.class \
	Filter.class \
	FilterCompOper.class \
	FilterElement.class \
	FilterElementCompOper.class \
	FilterModule.class \
	FilterType.class \
	Internal.class \
	MatchingPart.class \
	MatchingPattern.class \
	MatchingType.class \
        MessageSelector.class \
	Method.class \
	NameMatchingType.class \
	Not.class \
	Or.class \
	SEQfilterCompOper.class \
	SignatureMatchingType.class \
	SubstitutionPart.class \
	Target.class \
	True.class \
	ValueExpression.class \
	VoidFilterCompOper.class \
	VoidFilterElementCompOper.class \
	False.class

include ${ROOTDIR}default.mk
