ROOTDIR=../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=ExecutionLabels.class \
	ExecutionModel.class \
	ExecutionState.class \
	ExecutionTransition.class \
	FlowModel.class \
	FlowNode.class \
	FlowTransition.class \
	Message.class
	

include ${ROOTDIR}default.mk
