ROOTDIR=../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=GeneralUtils.class Logger.class Profiler.class StaticVariableReplacer.class WrappingUtil.class

include ${ROOTDIR}default.mk
