ROOTDIR=../../../../
include ${ROOTDIR}common.mk

SUBDIRS=filterxmlparser

CLASSES=AbstractVM.class \
	Resource.class \
	AbstractVM.class \
	ActionDescription.class \
	SECRET.class \
	ResourceDescription.class \
	SecretRepository.class \
	HTMLReporter.class \
	StandAloneDriver.class \
	ConflictReporter.class \
	ActionResourceDescription.class \
	FilterActionDescription.class

include ${ROOTDIR}default.mk
