ROOTDIR=../../../../../
include ${ROOTDIR}common.mk

SUBDIRS=

CLASSES=Compiler.class \
	CompilerException.class \
	CompilerFactory.class \
	ConfigCompiler.class \
	RealSourceManager.class

include ${ROOTDIR}default.mk
