// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
namespace TestDataStore
{
    /// <summary>
    ///This is a test class for Composestar.DataStore.LanguageModel.CallInfo and is intended
    ///to contain all Composestar.DataStore.LanguageModel.CallInfo Unit Tests
    ///</summary>
    [TestClass()]
    public class CallInfoFixture
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for MethodReference
        ///</summary>
        [TestMethod()]
        public void MethodReferenceTest()
        {
            global::Composestar.DataStore.LanguageModel.CallInfo target = new global::Composestar.DataStore.LanguageModel.CallInfo();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.MethodReference = val;


            Assert.AreEqual(val, target.MethodReference, "Composestar.DataStore.LanguageModel.CallInfo.MethodReference was not set correctl" +
                    "y.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

       

        /// <summary>
        ///A test for Object ()
        ///</summary>
        [TestMethod()]
        public void ConstructorTest()
        {
            object target = new global::Composestar.DataStore.LanguageModel.CallInfo();

            // TODO: Implement code to verify target
            Assert.Inconclusive("TODO: Implement code to verify target");
        }

       

    }


}
